name: Build go project

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      
      - name: Test compile
        run: go build .