name: Build go project

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      
      - name: Test compile
        run: go build .