name: Build & Push to container registry

on:
  release:
    types: [created]
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
    paths:
      - "Dockerfile"

jobs:
  docker:
    uses: frutbits/workflows/.github/workflows/build-docker-image.yml@main
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}